version: "3.9"

services:
  bot:
    build: .
    image: study-bot:latest
    container_name: study-bot
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./files:/files
    network_mode: "host"
  events-worker:
    image: study-bot:latest
    container_name: study-bot-events-worker
    restart: unless-stopped
    env_file: .env
    environment:
      APP_MODE: events-worker
    volumes:
      - ./files:/files
    network_mode: "host"
