;;; !!! This configuration is handled by HelloImGui and stores several Ini Files, separated by markers like this:
           ;;;<<<INI_NAME>>>;;;

;;;<<<ImGui_655921752_Default>>>;;;
[Window][Debug##Default]
Pos=60,60
Size=400,400
Collapsed=0

[Window][Graph Settings]
Pos=60,60
Size=164,141
Collapsed=1

[Window][Graph Controls]
Pos=920,20
Size=311,274
Collapsed=0

[Window][Node Details]
Pos=168,45
Size=885,642
Collapsed=1

[Table][0xB596925D,12]
Column 0  Weight=1.4526
Column 1  Weight=0.1421
Column 2  Weight=1.3895
Column 3  Weight=1.4053
Column 4  Weight=0.5842
Column 5  Weight=0.9947
Column 6  Weight=0.9947
Column 7  Weight=2.3211
Column 8  Weight=0.3632
Column 9  Weight=0.3316
Column 10 Weight=1.0105
Column 11 Weight=1.0105

[Docking][Data]

;;;<<<Layout_655921752_Default>>>;;;
;;;<<<HelloImGui_Misc>>>;;;
[Layout]
Name=Default
[StatusBar]
Show=false
ShowFps=true
[Theme]
Name=DarculaDarker
;;;<<<SplitIds>>>;;;
{"gImGuiSplitIDs":{}}
