CREATE TYPE "university_sector" AS ENUM (
  'public',
  'private',
  'online',
  'unknown'
);

CREATE TABLE "universities" (
  "university_id" varchar PRIMARY KEY NOT NULL,
  "display_name" varchar NOT NULL,
  "official_name" varchar,
  "city" varchar,
  "province" varchar,
  "region" varchar,
  "university_sector" university_sector NOT NULL DEFAULT 'unknown',
  "official_website" text,
  "qs_profile_url" text
);

CREATE TABLE "subjects" (
  "subject_slug" varchar PRIMARY KEY NOT NULL,
  "subject_name" varchar NOT NULL,
  "source_qs_url" text
);

CREATE TABLE "university_subject_rankings" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "university_id" varchar NOT NULL,
  "subject_slug" varchar NOT NULL,
  "ranking_year" int NOT NULL,
  "qs_subject_rank_display" varchar,
  "qs_subject_rank_numeric" int,
  "qs_subject_italy_rank" int,
  "qs_subject_score" decimal(5,1),
  "source_page_url" text
);

CREATE TABLE "university_global_rankings" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "university_id" varchar NOT NULL,
  "ranking_year" int NOT NULL,
  "qs_global_rank_display" varchar,
  "qs_global_rank_numeric" int,
  "qs_global_italy_rank" int,
  "qs_global_score" decimal(5,1),
  "source_page_url" text
);

CREATE INDEX "idx_universities_display_name" ON "universities" ("display_name");
CREATE INDEX "idx_universities_city" ON "universities" ("city");
CREATE INDEX "idx_universities_region" ON "universities" ("region");
CREATE INDEX "idx_universities_sector" ON "universities" ("university_sector");

CREATE INDEX "idx_subjects_subject_name" ON "subjects" ("subject_name");

CREATE UNIQUE INDEX "uq_university_subject_rankings_university_subject_year"
  ON "university_subject_rankings" ("university_id", "subject_slug", "ranking_year");
CREATE INDEX "idx_university_subject_rankings_subject_italy_rank"
  ON "university_subject_rankings" ("subject_slug", "qs_subject_italy_rank");

CREATE UNIQUE INDEX "uq_university_global_rankings_university_year"
  ON "university_global_rankings" ("university_id", "ranking_year");
CREATE INDEX "idx_university_global_rankings_italy_rank"
  ON "university_global_rankings" ("qs_global_italy_rank");

ALTER TABLE "university_subject_rankings"
  ADD FOREIGN KEY ("university_id") REFERENCES "universities" ("university_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "university_subject_rankings"
  ADD FOREIGN KEY ("subject_slug") REFERENCES "subjects" ("subject_slug") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "university_global_rankings"
  ADD FOREIGN KEY ("university_id") REFERENCES "universities" ("university_id") DEFERRABLE INITIALLY IMMEDIATE;
