CREATE TYPE "usage_event_type" AS ENUM (
  'message',
  'rag_query',
  'chat_completion',
  'embedding',
  'classification',
  'admin_action',
  'other'
);

CREATE TYPE "classifier_intent" AS ENUM (
  'GREETING',
  'CHIT_CHAT',
  'FACTUAL_QUESTION',
  'GUIDANCE',
  'DOCUMENT_REQUEST',
  'OTHER'
);

CREATE TYPE "auth_provider_type" AS ENUM (
  'telegram',
  'google',
  'password'
);

CREATE TABLE "users" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "telegram_id" bigint,
  "email" varchar(320),
  "email_verified_at" timestamptz,
  "password_hash" text,
  "username" varchar(255),
  "first_name" varchar(255),
  "last_name" varchar(255),
  "is_blocked" boolean NOT NULL DEFAULT false,
  "is_admin" boolean NOT NULL DEFAULT false,
  "access_expires_at" timestamptz,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "user_auth_providers" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" bigint NOT NULL REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE,
  "provider" auth_provider_type NOT NULL,
  "provider_user_id" varchar(255) NOT NULL,
  "provider_email" varchar(320),
  "provider_username" varchar(255),
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "user_sessions" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" bigint NOT NULL REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE,
  "refresh_token_hash" text NOT NULL,
  "user_agent" text,
  "ip_address" inet,
  "expires_at" timestamptz NOT NULL,
  "revoked_at" timestamptz,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "password_reset_tokens" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" bigint NOT NULL REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE,
  "token_hash" text NOT NULL,
  "expires_at" timestamptz NOT NULL,
  "used_at" timestamptz,
  "created_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE UNIQUE INDEX "uq_users_telegram_id" ON "users" ("telegram_id");
CREATE UNIQUE INDEX "uq_users_email" ON "users" ("email");
CREATE INDEX "idx_users_username" ON "users" ("username");
CREATE INDEX "idx_users_is_blocked" ON "users" ("is_blocked");
CREATE INDEX "idx_users_is_admin" ON "users" ("is_admin");
CREATE INDEX "idx_users_access_expires_at" ON "users" ("access_expires_at");

CREATE UNIQUE INDEX "uq_user_auth_providers_provider_user_id" ON "user_auth_providers" ("provider", "provider_user_id");
CREATE INDEX "idx_user_auth_providers_user_id" ON "user_auth_providers" ("user_id");
CREATE INDEX "idx_user_auth_providers_provider_email" ON "user_auth_providers" ("provider_email");

CREATE INDEX "idx_user_sessions_user_id" ON "user_sessions" ("user_id");
CREATE UNIQUE INDEX "uq_user_sessions_refresh_token_hash" ON "user_sessions" ("refresh_token_hash");
CREATE INDEX "idx_user_sessions_expires_at" ON "user_sessions" ("expires_at");
CREATE INDEX "idx_user_sessions_revoked_at" ON "user_sessions" ("revoked_at");

CREATE INDEX "idx_password_reset_tokens_user_id" ON "password_reset_tokens" ("user_id");
CREATE UNIQUE INDEX "uq_password_reset_tokens_token_hash" ON "password_reset_tokens" ("token_hash");
CREATE INDEX "idx_password_reset_tokens_expires_at" ON "password_reset_tokens" ("expires_at");
CREATE INDEX "idx_password_reset_tokens_used_at" ON "password_reset_tokens" ("used_at");

COMMENT ON TABLE "users" IS 'Internal application user. A user may authenticate through Telegram, password login, Google OAuth, or multiple linked providers. password_hash must store only a secure hash, never the raw password. Application logic should derive access: blocked users are denied; otherwise null access_expires_at means unlimited, and future access_expires_at means active. updated_at should be maintained by trigger or application logic.';
COMMENT ON COLUMN "users"."telegram_id" IS 'Nullable. Stable Telegram user ID if the user comes from Telegram';
COMMENT ON COLUMN "users"."email" IS 'Nullable. Used for admin panel login, password login, or OAuth login';
COMMENT ON COLUMN "users"."email_verified_at" IS 'Nullable. Set when email is verified through OAuth or email verification';
COMMENT ON COLUMN "users"."password_hash" IS 'Nullable. Stores bcrypt or argon2 hash only. Null means password login is disabled';
COMMENT ON COLUMN "users"."username" IS 'Nullable. Current platform username/handle. Can change or be removed';
COMMENT ON COLUMN "users"."access_expires_at" IS 'Nullable. Null means unlimited access';

COMMENT ON TABLE "user_auth_providers" IS 'Links internal users to external authentication providers. For Google OAuth, provider_user_id should store the stable Google sub claim, not just email.';
COMMENT ON COLUMN "user_auth_providers"."provider_user_id" IS 'External stable user ID from provider. For Google, store the sub claim. For Telegram, store Telegram ID as string';
COMMENT ON COLUMN "user_auth_providers"."provider_email" IS 'Email returned by provider, if available';
COMMENT ON COLUMN "user_auth_providers"."provider_username" IS 'Username or handle returned by provider, if available';

COMMENT ON TABLE "user_sessions" IS 'Stores active login sessions for admin panel or web app. Store only hashed refresh/session tokens. Short-lived access tokens can be JWTs and do not need to be stored.';
COMMENT ON COLUMN "user_sessions"."refresh_token_hash" IS 'Hash of refresh token/session token. Never store raw token';

COMMENT ON TABLE "password_reset_tokens" IS 'Stores password reset tokens for password login users. Store only hashed tokens, never raw reset tokens.';
COMMENT ON COLUMN "password_reset_tokens"."token_hash" IS 'Hash of password reset token. Never store raw token';
