CREATE TYPE "usage_event_type" AS ENUM (
  'message',
  'rag_query',
  'chat_completion',
  'embedding',
  'classification',
  'admin_action',
  'other'
);

CREATE TYPE "classifier_intent" AS ENUM (
  'GREETING',
  'CHIT_CHAT',
  'FACTUAL_QUESTION',
  'GUIDANCE',
  'DOCUMENT_REQUEST',
  'OTHER'
);

CREATE TABLE "users" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "telegram_id" bigint UNIQUE NOT NULL,
  "telegram_username" varchar(255),
  "first_name" varchar(255),
  "last_name" varchar(255),
  "is_blocked" boolean NOT NULL DEFAULT false,
  "is_admin" boolean NOT NULL DEFAULT false,
  "has_access" boolean NOT NULL DEFAULT true,
  "access_expires_at" timestamptz,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE INDEX "idx_users_telegram_username" ON "users" ("telegram_username");
CREATE INDEX "idx_users_is_blocked" ON "users" ("is_blocked");
CREATE INDEX "idx_users_is_admin" ON "users" ("is_admin");
CREATE INDEX "idx_users_has_access" ON "users" ("has_access");
CREATE INDEX "idx_users_access_expires_at" ON "users" ("access_expires_at");

COMMENT ON COLUMN "users"."telegram_id" IS 'Stable Telegram user ID used as the primary external identifier';
COMMENT ON COLUMN "users"."telegram_username" IS 'Nullable. Telegram username can change over time or be removed by the user';
COMMENT ON COLUMN "users"."access_expires_at" IS 'Nullable. Null can mean no expiration';
