CREATE TYPE "usage_event_type" AS ENUM (
  'message',
  'rag_query',
  'chat_completion',
  'embedding',
  'classification',
  'admin_action',
  'other'
);

CREATE TYPE "classifier_intent" AS ENUM (
  'GREETING',
  'CHIT_CHAT',
  'FACTUAL_QUESTION',
  'GUIDANCE',
  'DOCUMENT_REQUEST',
  'OTHER'
);

CREATE TABLE "users" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "telegram_id" bigint NOT NULL,
  "username" varchar(255),
  "first_name" varchar(255),
  "last_name" varchar(255),
  "is_blocked" boolean NOT NULL DEFAULT false,
  "is_admin" boolean NOT NULL DEFAULT false,
  "access_expires_at" timestamptz,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now()),
  CONSTRAINT "uq_users_telegram_id" UNIQUE ("telegram_id")
);

CREATE INDEX "idx_users_username" ON "users" ("username");
CREATE INDEX "idx_users_is_blocked" ON "users" ("is_blocked");
CREATE INDEX "idx_users_is_admin" ON "users" ("is_admin");
CREATE INDEX "idx_users_access_expires_at" ON "users" ("access_expires_at");

COMMENT ON TABLE "users" IS 'Application logic should derive access: blocked users are denied; otherwise null access_expires_at means unlimited, and future access_expires_at means active. updated_at should be maintained by trigger or application logic.';
COMMENT ON COLUMN "users"."telegram_id" IS 'Stable Telegram user ID used as the main external identifier';
COMMENT ON COLUMN "users"."username" IS 'Nullable. Current platform username/handle. Can change or be removed';
COMMENT ON COLUMN "users"."access_expires_at" IS 'Nullable. Null means unlimited access';
