CREATE TABLE "messages" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" bigint REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE,
  "message_text" text NOT NULL,
  "language_code" varchar(16),
  "telegram_message_id" bigint,
  "created_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE INDEX "idx_messages_user_id" ON "messages" ("user_id");
CREATE INDEX "idx_messages_telegram_message_id" ON "messages" ("telegram_message_id");
CREATE INDEX "idx_messages_created_at" ON "messages" ("created_at");

COMMENT ON TABLE "messages" IS 'Stores user messages.';
COMMENT ON COLUMN "messages"."user_id" IS 'User who sent the message';
COMMENT ON COLUMN "messages"."message_text" IS 'Original message text';

CREATE TABLE "message_classifications" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "message_id" bigint UNIQUE NOT NULL REFERENCES "messages" ("id") DEFERRABLE INITIALLY IMMEDIATE,
  "intent" classifier_intent NOT NULL,
  "explain" text,
  "detected_language" varchar(32),
  "classifier_model" varchar(100),
  "classifier_version" varchar(100),
  "created_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE INDEX "idx_message_classifications_intent" ON "message_classifications" ("intent");
CREATE INDEX "idx_message_classifications_detected_language" ON "message_classifications" ("detected_language");
CREATE INDEX "idx_message_classifications_classifier_model" ON "message_classifications" ("classifier_model");
CREATE INDEX "idx_message_classifications_created_at" ON "message_classifications" ("created_at");

COMMENT ON TABLE "message_classifications" IS 'Stores classification output from classify_query(): intent, explain, and language.';
COMMENT ON COLUMN "message_classifications"."explain" IS 'Short explanation returned by classifier';
COMMENT ON COLUMN "message_classifications"."detected_language" IS 'Language returned by classifier, for example ru or Russian';
COMMENT ON COLUMN "message_classifications"."classifier_model" IS 'For example gpt-4o-mini';
COMMENT ON COLUMN "message_classifications"."classifier_version" IS 'Optional prompt version or ruleset version';