CREATE TABLE "conversations" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" bigint NOT NULL REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE,
  "conversation_key" varchar(255) NOT NULL,
  "summary" text,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE UNIQUE INDEX "uq_conversations_conversation_key" ON "conversations" ("conversation_key");
CREATE INDEX "idx_conversations_user_id" ON "conversations" ("user_id");
CREATE INDEX "idx_conversations_created_at" ON "conversations" ("created_at");
CREATE INDEX "idx_conversations_updated_at" ON "conversations" ("updated_at");

COMMENT ON TABLE "conversations" IS 'Groups user messages into logical conversation threads. updated_at should be maintained by trigger or application logic.';
COMMENT ON COLUMN "conversations"."conversation_key" IS 'Stable external conversation key used for Redis/session correlation and persistence';
COMMENT ON COLUMN "conversations"."summary" IS 'Optional latest running summary of the conversation';

CREATE TABLE "messages" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "conversation_id" bigint NOT NULL REFERENCES "conversations" ("id") DEFERRABLE INITIALLY IMMEDIATE,
  "message_text" text NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE INDEX "idx_messages_conversation_id" ON "messages" ("conversation_id");
CREATE INDEX "idx_messages_created_at" ON "messages" ("created_at");
CREATE INDEX "idx_messages_conversation_created_at" ON "messages" ("conversation_id", "created_at");

COMMENT ON TABLE "messages" IS 'Stores only user messages for the MVP.';
COMMENT ON COLUMN "messages"."conversation_id" IS 'Conversation/thread this message belongs to';
COMMENT ON COLUMN "messages"."message_text" IS 'Original user message text';

CREATE TABLE "message_classifications" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "message_id" bigint UNIQUE NOT NULL REFERENCES "messages" ("id") DEFERRABLE INITIALLY IMMEDIATE,
  "intent" classifier_intent NOT NULL,
  "explanation" text,
  "detected_language" varchar(16),
  "classifier_model" varchar(128),
  "classifier_version" varchar(128),
  "created_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE INDEX "idx_message_classifications_intent" ON "message_classifications" ("intent");
CREATE INDEX "idx_message_classifications_detected_language" ON "message_classifications" ("detected_language");
CREATE INDEX "idx_message_classifications_classifier_model" ON "message_classifications" ("classifier_model");
CREATE INDEX "idx_message_classifications_created_at" ON "message_classifications" ("created_at");

COMMENT ON TABLE "message_classifications" IS 'Stores one current classification result per message. If classification history is needed later, remove the unique constraint on message_id.';
COMMENT ON COLUMN "message_classifications"."explanation" IS 'Optional short explanation returned by classifier';
COMMENT ON COLUMN "message_classifications"."detected_language" IS 'Language code returned by classifier, for example kk, ru, en, zh-CN, or other';
COMMENT ON COLUMN "message_classifications"."classifier_model" IS 'For example gpt-4o-mini';
COMMENT ON COLUMN "message_classifications"."classifier_version" IS 'Optional prompt version or ruleset version';
