CREATE TABLE "usage_events" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" bigint NOT NULL REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE,
  "event_type" usage_event_type NOT NULL,
  "input_tokens" integer NOT NULL DEFAULT 0,
  "output_tokens" integer NOT NULL DEFAULT 0,
  "total_tokens" integer NOT NULL DEFAULT 0,
  "estimated_cost" numeric(14,6) NOT NULL DEFAULT 0,
  "created_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE INDEX "idx_usage_events_user_created_at" ON "usage_events" ("user_id", "created_at");
CREATE INDEX "idx_usage_events_event_type" ON "usage_events" ("event_type");
CREATE INDEX "idx_usage_events_created_at" ON "usage_events" ("created_at");

COMMENT ON TABLE "usage_events" IS 'Cost/accounting-focused event log.';

CREATE TABLE "admin_actions" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "admin_user_id" bigint NOT NULL REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE,
  "target_user_id" bigint REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE,
  "action_type" varchar(100) NOT NULL,
  "entity_type" varchar(50),
  "entity_id" bigint,
  "notes" text,
  "created_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE INDEX "idx_admin_actions_admin_user_id" ON "admin_actions" ("admin_user_id");
CREATE INDEX "idx_admin_actions_target_user_id" ON "admin_actions" ("target_user_id");
CREATE INDEX "idx_admin_actions_entity" ON "admin_actions" ("entity_type", "entity_id");
CREATE INDEX "idx_admin_actions_created_at" ON "admin_actions" ("created_at");

COMMENT ON TABLE "admin_actions" IS 'Audit trail for admin panel operations.';
COMMENT ON COLUMN "admin_actions"."action_type" IS 'Examples: grant_access, revoke_access, block_user, unblock_user';
COMMENT ON COLUMN "admin_actions"."entity_type" IS 'user, message';
COMMENT ON COLUMN "admin_actions"."entity_id" IS 'ID of affected entity';