CREATE TYPE "admin_action_type" AS ENUM (
  'grant_access',
  'revoke_access',
  'block_user',
  'unblock_user',
  'verify_payment',
  'extend_access',
  'classify_message',
  'login',
  'logout',
  'other'
);

CREATE TYPE "admin_entity_type" AS ENUM (
  'user',
  'message',
  'conversation',
  'usage_event',
  'session',
  'auth_provider',
  'other'
);

CREATE TABLE "usage_events" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" bigint NOT NULL REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE,
  "conversation_id" bigint REFERENCES "conversations" ("id") DEFERRABLE INITIALLY IMMEDIATE,
  "message_id" bigint REFERENCES "messages" ("id") DEFERRABLE INITIALLY IMMEDIATE,
  "event_type" usage_event_type NOT NULL,
  "input_tokens" integer NOT NULL DEFAULT 0,
  "output_tokens" integer NOT NULL DEFAULT 0,
  "estimated_cost" numeric(14,6) NOT NULL DEFAULT 0,
  "created_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE INDEX "idx_usage_events_user_created_at" ON "usage_events" ("user_id", "created_at");
CREATE INDEX "idx_usage_events_conversation_id" ON "usage_events" ("conversation_id");
CREATE INDEX "idx_usage_events_message_id" ON "usage_events" ("message_id");
CREATE INDEX "idx_usage_events_event_type" ON "usage_events" ("event_type");
CREATE INDEX "idx_usage_events_created_at" ON "usage_events" ("created_at");

COMMENT ON TABLE "usage_events" IS 'Append-only usage and accounting log. Token totals should be derived in queries as input_tokens + output_tokens.';
COMMENT ON COLUMN "usage_events"."conversation_id" IS 'Nullable. Set when event relates to a specific conversation';
COMMENT ON COLUMN "usage_events"."message_id" IS 'Nullable. Set when event relates to a specific message';
COMMENT ON COLUMN "usage_events"."estimated_cost" IS 'Estimated cost stored for reporting/accounting';

CREATE TABLE "monthly_usage" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" bigint NOT NULL REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE,
  "usage_month" date NOT NULL,
  "total_input_tokens" bigint NOT NULL DEFAULT 0,
  "total_output_tokens" bigint NOT NULL DEFAULT 0,
  "total_tokens" bigint NOT NULL DEFAULT 0,
  "total_estimated_cost" numeric(14,6) NOT NULL DEFAULT 0,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE UNIQUE INDEX "uq_monthly_usage_user_month" ON "monthly_usage" ("user_id", "usage_month");
CREATE INDEX "idx_monthly_usage_usage_month" ON "monthly_usage" ("usage_month");

COMMENT ON TABLE "monthly_usage" IS 'Stores per-user monthly usage aggregates for fast quota checks and reporting. Should be updated by application logic whenever a new usage_event is inserted.';
COMMENT ON COLUMN "monthly_usage"."usage_month" IS 'First day of the month in UTC, for example 2026-04-01';

CREATE TABLE "admin_actions" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "admin_user_id" bigint NOT NULL REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE,
  "target_user_id" bigint REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE,
  "action_type" admin_action_type NOT NULL,
  "entity_type" admin_entity_type,
  "entity_id" bigint,
  "notes" text,
  "created_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE INDEX "idx_admin_actions_admin_user_id" ON "admin_actions" ("admin_user_id");
CREATE INDEX "idx_admin_actions_target_user_id" ON "admin_actions" ("target_user_id");
CREATE INDEX "idx_admin_actions_action_type" ON "admin_actions" ("action_type");
CREATE INDEX "idx_admin_actions_entity" ON "admin_actions" ("entity_type", "entity_id");
CREATE INDEX "idx_admin_actions_created_at" ON "admin_actions" ("created_at");

COMMENT ON TABLE "admin_actions" IS 'Audit trail for admin panel operations.';
COMMENT ON COLUMN "admin_actions"."entity_type" IS 'Logical type of affected entity';
COMMENT ON COLUMN "admin_actions"."entity_id" IS 'ID of affected entity. Polymorphic reference, so not enforced by a foreign key';
