DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_type
    WHERE typname = 'auth_provider_type'
  ) THEN
    CREATE TYPE "auth_provider_type" AS ENUM (
      'telegram',
      'google',
      'password'
    );
  END IF;
END $$;

ALTER TYPE "admin_action_type" ADD VALUE IF NOT EXISTS 'login';
ALTER TYPE "admin_action_type" ADD VALUE IF NOT EXISTS 'logout';

ALTER TYPE "admin_entity_type" ADD VALUE IF NOT EXISTS 'session';
ALTER TYPE "admin_entity_type" ADD VALUE IF NOT EXISTS 'auth_provider';

ALTER TABLE "users"
  ALTER COLUMN "telegram_id" DROP NOT NULL,
  ADD COLUMN IF NOT EXISTS "email" varchar(320),
  ADD COLUMN IF NOT EXISTS "email_verified_at" timestamptz,
  ADD COLUMN IF NOT EXISTS "password_hash" text;

CREATE UNIQUE INDEX IF NOT EXISTS "uq_users_email" ON "users" ("email");

COMMENT ON TABLE "users" IS 'Internal application user. A user may authenticate through Telegram, password login, Google OAuth, or multiple linked providers. password_hash must store only a secure hash, never the raw password. Application logic should derive access: blocked users are denied; otherwise null access_expires_at means unlimited, and future access_expires_at means active. updated_at should be maintained by trigger or application logic.';
COMMENT ON COLUMN "users"."telegram_id" IS 'Nullable. Stable Telegram user ID if the user comes from Telegram';
COMMENT ON COLUMN "users"."email" IS 'Nullable. Used for admin panel login, password login, or OAuth login';
COMMENT ON COLUMN "users"."email_verified_at" IS 'Nullable. Set when email is verified through OAuth or email verification';
COMMENT ON COLUMN "users"."password_hash" IS 'Nullable. Stores bcrypt or argon2 hash only. Null means password login is disabled';

CREATE TABLE IF NOT EXISTS "user_auth_providers" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" bigint NOT NULL REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE,
  "provider" auth_provider_type NOT NULL,
  "provider_user_id" varchar(255) NOT NULL,
  "provider_email" varchar(320),
  "provider_username" varchar(255),
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE UNIQUE INDEX IF NOT EXISTS "uq_user_auth_providers_provider_user_id" ON "user_auth_providers" ("provider", "provider_user_id");
CREATE INDEX IF NOT EXISTS "idx_user_auth_providers_user_id" ON "user_auth_providers" ("user_id");
CREATE INDEX IF NOT EXISTS "idx_user_auth_providers_provider_email" ON "user_auth_providers" ("provider_email");

COMMENT ON TABLE "user_auth_providers" IS 'Links internal users to external authentication providers. For Google OAuth, provider_user_id should store the stable Google sub claim, not just email.';
COMMENT ON COLUMN "user_auth_providers"."provider_user_id" IS 'External stable user ID from provider. For Google, store the sub claim. For Telegram, store Telegram ID as string';
COMMENT ON COLUMN "user_auth_providers"."provider_email" IS 'Email returned by provider, if available';
COMMENT ON COLUMN "user_auth_providers"."provider_username" IS 'Username or handle returned by provider, if available';

CREATE TABLE IF NOT EXISTS "user_sessions" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" bigint NOT NULL REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE,
  "refresh_token_hash" text NOT NULL,
  "user_agent" text,
  "ip_address" inet,
  "expires_at" timestamptz NOT NULL,
  "revoked_at" timestamptz,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE UNIQUE INDEX IF NOT EXISTS "uq_user_sessions_refresh_token_hash" ON "user_sessions" ("refresh_token_hash");
CREATE INDEX IF NOT EXISTS "idx_user_sessions_user_id" ON "user_sessions" ("user_id");
CREATE INDEX IF NOT EXISTS "idx_user_sessions_expires_at" ON "user_sessions" ("expires_at");
CREATE INDEX IF NOT EXISTS "idx_user_sessions_revoked_at" ON "user_sessions" ("revoked_at");

COMMENT ON TABLE "user_sessions" IS 'Stores active login sessions for admin panel or web app. Store only hashed refresh/session tokens. Short-lived access tokens can be JWTs and do not need to be stored.';
COMMENT ON COLUMN "user_sessions"."refresh_token_hash" IS 'Hash of refresh token/session token. Never store raw token';

CREATE TABLE IF NOT EXISTS "password_reset_tokens" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" bigint NOT NULL REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE,
  "token_hash" text NOT NULL,
  "expires_at" timestamptz NOT NULL,
  "used_at" timestamptz,
  "created_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE UNIQUE INDEX IF NOT EXISTS "uq_password_reset_tokens_token_hash" ON "password_reset_tokens" ("token_hash");
CREATE INDEX IF NOT EXISTS "idx_password_reset_tokens_user_id" ON "password_reset_tokens" ("user_id");
CREATE INDEX IF NOT EXISTS "idx_password_reset_tokens_expires_at" ON "password_reset_tokens" ("expires_at");
CREATE INDEX IF NOT EXISTS "idx_password_reset_tokens_used_at" ON "password_reset_tokens" ("used_at");

COMMENT ON TABLE "password_reset_tokens" IS 'Stores password reset tokens for password login users. Store only hashed tokens, never raw reset tokens.';
COMMENT ON COLUMN "password_reset_tokens"."token_hash" IS 'Hash of password reset token. Never store raw token';

CREATE TABLE IF NOT EXISTS "monthly_usage" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" bigint NOT NULL REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE,
  "usage_month" date NOT NULL,
  "total_input_tokens" bigint NOT NULL DEFAULT 0,
  "total_output_tokens" bigint NOT NULL DEFAULT 0,
  "total_tokens" bigint NOT NULL DEFAULT 0,
  "total_estimated_cost" numeric(14,6) NOT NULL DEFAULT 0,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE UNIQUE INDEX IF NOT EXISTS "uq_monthly_usage_user_month" ON "monthly_usage" ("user_id", "usage_month");
CREATE INDEX IF NOT EXISTS "idx_monthly_usage_usage_month" ON "monthly_usage" ("usage_month");

COMMENT ON TABLE "monthly_usage" IS 'Stores per-user monthly usage aggregates for fast quota checks and reporting. Should be updated by application logic whenever a new usage_event is inserted.';
COMMENT ON COLUMN "monthly_usage"."usage_month" IS 'First day of the month in UTC, for example 2026-04-01';
